name: Solicitud de Mejora
description: Reportar una mejora al sistema (cualquier miembro del equipo)
title: "[Mejora] "
labels: ["mejora"]
body:
  - type: textarea
    id: descripcion
    attributes:
      label: Descripción de la mejora
      placeholder: "Describe qué se debe mejorar y por qué"
    validations:
      required: true
  - type: dropdown
    id: prioridad
    attributes:
      label: Prioridad
      options:
        - baja
        - media
        - alta
